### ISSUE TITLE
Water heater state not available after 1.2.17 update

### ISSUE THREAD

**Issue by ollila** [veista/nilan#153]
After updating to 1.2.17 neither top nor bottom water heater provided state information (idle/heating) neither in UI nor logbook. Looking at the commit from update notes this was probably intentional change of functionality but as side effect it removed sensor to see if electrical heating is activated or not.

My unit is VP 18cek, FW 1.6.52, hardware 16 and modbus version 22.

**Comment by veista** [comment]
I know. There was no elegant way to implement that, since the water heater entity sucks in HA. I added as a quick workaround it to the extra attributes of the water heater element so the information can be easily extracted out with a template sensor. Please do not ask for a premade sensor for this. I will wait for the water heater entity to be fixed in HA (been waiting for 2 years).
